Repository hi-teen/backend, pull requests merged in 2025-08, with the labels that each got.

#98 [fix/#97]: 예외처리 로직 수정
  src/main/java/backend/hiteen/auth/service/AuthService.java
  src/main/java/backend/hiteen/board/controller/BoardController.java
  src/main/java/backend/hiteen/board/exception/BoardCreationFailedException.java
  src/main/java/backend/hiteen/board/exception/KeywordRequiredException.java
  src/main/java/backend/hiteen/board/exception/NoPermissionToDeleteBoardException.java
  src/main/java/backend/hiteen/board/service/BoardService.java
  src/main/java/backend/hiteen/love/exception/LoveAlreadyExistsException.java
  src/main/java/backend/hiteen/love/exception/LoveNotFoundException.java
  src/main/java/backend/hiteen/love/service/LoveService.java
  src/main/java/backend/hiteen/member/exception/MemberAlreadyExistsException.java
  src/main/java/backend/hiteen/member/exception/MemberPasswordNotMatchException.java
  src/main/java/backend/hiteen/member/exception/MemberRefreshTokenMismatchException.java
  src/main/java/backend/hiteen/member/exception/MemberRefreshTokenNotFoundException.java
  src/main/java/backend/hiteen/member/exception/MemberUnauthorizedException.java
  src/main/java/backend/hiteen/member/service/MemberService.java
  src/main/java/backend/hiteen/scrap/exception/ScrapAlreadyExistsException.java
  src/main/java/backend/hiteen/scrap/exception/ScrapNotFoundException.java
  src/main/java/backend/hiteen/scrap/service/ScrapService.java
Labels: Fix

#100 [feat/#99]: 이메일 중복 확인 기능 구현
  src/main/java/backend/hiteen/common/response/ErrorCode.java
  src/main/java/backend/hiteen/common/response/SuccessCode.java
  src/main/java/backend/hiteen/global/config/SecurityConfig.java
  src/main/java/backend/hiteen/member/controller/MemberController.java
  src/main/java/backend/hiteen/member/service/MemberService.java
Labels: Feat

#105 refactor : 학교 검색 api 응답 교육청이름 추가
  src/main/java/backend/hiteen/externalapi/school/dto/SchoolSearchResponse.java
  src/main/java/backend/hiteen/externalapi/school/service/SchoolService.java
Labels: Refactor
